version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"

  db:
    image: postgres
    ports:
      - "8000:5432"
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "product_info"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./database/csv:/var/csv